{
 "title": "STToolkit Crowding Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sensor",
    "label": "Sensor",
    "query": "from(bucket: \"DetectionsDB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetectionstable\")\r\n  |> group(columns: [\"device\"])\r\n  |> distinct(column: \"device\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "System General Information",
   "type": "table",
   "description": "This table alows you to visualize the general information of the crowding monitoring system. You can observe the last sensor location measurement sent,  the last crowding measurement sent by each sensor, and the last number of detected devices by each sensor.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "t1 = from(bucket: \"DetectionsDB\")\r\n  |> range(start: 2023-09-01T00:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorLocation\" )\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n\r\n\r\nt2 = from(bucket: \"DetectionsDB\")\r\n  |> range(start: 2023-09-01T00:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetectionstable\" )\r\n  |> filter(fn: (r) => r[\"type_data\"] == \"all\")\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n\r\n\r\njoin( tables: {t1: t1, t2: t2}, on: [\"device\"])\r\n  |> group(columns: [\"device\"])\r\n  |> last(column: \"devices_detected\")\r\n  |> rename(columns: {device: \"Sensor\", _time_t1: \"Last Location\",_time_t2: \"Last Record\", devices_detected: \"Detected devices\"}) \r\n  |> drop(columns:[\"latitude\", \"longitude\",\"_measurement_t1\", \"_measurement_t2\",\"ipaddress\", \"macAddress\",\"type_data\",\"tecnology\",\"ipAddress\", \"location\"])  \r\n  |> group()"
    }
   ]
  },
  {
   "title": "Crowding Geodistribution",
   "type": "geomap",
   "description": "This panel shows the crowding geodistributions at the several locations where the sensors are currently deployed. Each sensor is represented in a heatmap circle with the number of detected devices in its proximity from the last measurement.\n\nYou can set the inicial view of this panel by selecting 'Edit', and  then using the 'Map view' tab. \n Specify the latitute and longitude coordinates for the initial view of this map when entering on this dashboard.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "t1 = from(bucket: \"DetectionsDB\")\n  |> range(start: 2023-09-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorLocation\" )\n  |> drop(columns:[\"_start\", \"_stop\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n\n\nt2 = from(bucket: \"DetectionsDB\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetectionstable\" )\n  |> filter(fn: (r) => r[\"type_data\"] == \"all\")\n  |> drop(columns:[\"_start\", \"_stop\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n\n\njoin( tables: {t1: t1, t2: t2}, on: [\"device\"])\n  |> group(columns: [\"device\"])\n  |> last(column: \"devices_detected\")\n  |> rename(columns: {_time_t1: \"Deployment Date\", _time_t2: \"Last Record\" })\n  |> drop(columns:[\"_measurement_t1\", \"_measurement_t2\",\"ipaddress\", \"macAddress\",\"type_data\",\"tecnology\"])\n  |> group()"
    }
   ]
  },
  {
   "title": "Crowding Comparison",
   "type": "timeseries",
   "description": "This graph allows you to visualize the crowding measurements sent by the sensors. Choose the sensors you want to visualize using the 'Sensor' button on the top left corner.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"DetectionsDB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetectionstable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  |> filter(fn: (r) => contains(value: r[\"device\"], set: ${Sensor:json}))\r\n  |> filter(fn: (r) => r[\"type_data\"] == \"all\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.device}))"
    }
   ]
  }
 ]
}